---
- name: Prepare environment
  tags: prepare_env
  block:
    - name: Install prerequisites
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - maven
        - openjdk-11-jdk-headless
        - docker-ce
      tags: install_prereqs

    - name: Build and run tests
      block:
        - name: Clean and verify project
          shell: |
            cd "{{ tests_directory }}" &&
            mvn clean verify -Dsurefire.skip=false -Dbrowser.type={{ browser_type }}
          when: browser_type is defined
          tags: run_tests

        - name: Delete target directory after testing
          file:
            path: "{{ tests_directory }}/target"
            state: absent
          ignore_errors: true
          tags: cleanup_target