---
- name: Verify Selenoid Status
  shell: "curl -I http://localhost:{{ selenoid_port }}"
  register: selenoid_status
  changed_when: false

- name: Display Selenoid Status
  debug:
    msg: "Selenoid is running on port {{ selenoid_port }}. Status: {{ selenoid_status.stdout_lines }}"